FROM golang:1.19.2-alpine3.16 AS proto
RUN apk add --no-cache make protobuf nodejs npm

WORKDIR /src
COPY . .

WORKDIR /src/protobuf
RUN npm ci

WORKDIR /src
RUN make proto

FROM alpine:3.8
WORKDIR /src
COPY --from=proto /src/protobuf /src/protobuf
