version: '3.6'

services:

  server:
    image: jf/magnolia.server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    container_name: "magnolia-server"
    ports:
      - "3004:3004"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -debug
    
  twitch-reader:
    image: jf/magnolia.twitch-reader
    build:
      context: .
      dockerfile: ./Dockerfile
      target: twitch_reader
    container_name: "magnolia-twitch-reader"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -debug
    
  chat-bot:
    image: jf/magnolia.chat-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "magnolia-chat-bot"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -debug

  markov-generator:
    image: jf/magnolia.markov-generator
    build:
      context: .
      dockerfile: ./Dockerfile
      target: markov_generator
    container_name: "magnolia-markov-generator"
    ports:
      - "3011:3011"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /app/config.toml
      
networks:
  magnolia:
    name: magnolia
    external: true
