version: '3.6'

## Access redis and mongo running on the host
## by specifying the address as host.docker.internal
# extra_hosts:
# - "host.docker.internal:host-gateway"

services:
  server:
    image: jf/magnolia.server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "magnolia-server"
    ports:
      - "3004:3004"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  magnolia:
    name: magnolia
    external: true