version: '3.6'

## Access redis and mongo running on the host
## by specifying the address as host.docker.internal
# extra_hosts:
# - "host.docker.internal:host-gateway"

services:
  server:
    image: jf/magnolia.server
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: "magnolia-server"
    ports:
      - "3004:3004"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -debug
  twitch-reader:
    image: jf/magnolia.twitch-reader
    build:
      context: .
      dockerfile: ./cmd/twitch-reader/Dockerfile
    container_name: "magnolia-twitch-reader"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -debug

  markov-generator:
    image: jf/magnolia.markov-generator
    build:
      context: .
      dockerfile: ./markov-generator/Dockerfile
    container_name: "magnolia-markov-generator"
    ports:
      - "3011:3011"
    networks:
      - "magnolia"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /app/config.json
      
networks:
  magnolia:
    name: magnolia
    external: true
