FROM golang:1.19.2-alpine3.16 AS proto
RUN apk add --no-cache make protobuf nodejs npm

WORKDIR /src
COPY . .

WORKDIR /src/protobuf
RUN npm ci

WORKDIR /src
RUN make proto

FROM golang:1.19.2-alpine3.16 AS build

ENV GOCACHE /go/cache

WORKDIR /src
COPY . .

COPY --from=proto /src/protobuf /src/protobuf
RUN go mod download
RUN go build -o /bin/out /src/cmd/server/main.go

FROM alpine:3.16
WORKDIR /src
COPY --from=proto /src/protobuf /src/protobuf
COPY --from=build /go/cache /go/cache
