name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install and setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Dependencies
        run: |
          sudo apt install -y make
          cd protobuf
          npm ci
          cd ..
          make proto
          go get -v -t -d ./...

      - name: Generate Codecov
        run: go test -race -v -count=1 -coverprofile=coverage.out ./...
