name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PBKIT_VERSION: 0.0.57

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - run: sudo apt install -y make git
    
      - uses: actions/checkout@v2

      - name: Install and setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.1

      - name: Setup pbkit
        run: |
          git clone -b "v${{ env.PBKIT_VERSION }}" https://github.com/pbkit/pbkit.git pbkit
          cd pbkit
          deno -n pb -A --unstable cli/pb/entrypoint.ts

      - name: Get Dependencies
        run: |
          make proto
          go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./...
