name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install and setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.1

      - name: Get Dependencies
        run: |
          sudo apt install -y make
          make proto
          go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./...
