name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PBKIT_VERSION: 0.0.57

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install and setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.1

      - uses: wei/curl@master
        with:
          args: https://github.com/pbkit/pbkit/releases/download/v${{ env.PBKIT_VERSION }}/pbkit-x86_64-unknown-linux-gnu.tar -o pbkit.tar
      
      - uses: montudor/action-zip@v1
        with:
          args: -xvf pbkit.tar

      - run: sudo mv pbkit /usr/local/bin

      - name: Get Dependencies
        run: |
          sudo apt install -y make
          make proto
          go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./...
